<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Core vs normal modules
    |--------------------------------------------------------------------------
    | Core modules (users, configuration) are always available per tenant.
    | Normal modules (items, etc.) are optional; enable per tenant as needed.
    | Only core module migrations are run during tenant provisioning.
    */
    'core_migration_tags' => [
        'inovcom-users-migrations',
    ],

    'sidebar_groups' => [
        'catalogue' => 'Catalogue',
        'ventes' => 'Ventes',
        'pharmacy' => 'Pharmacie',
        'achats_stock' => 'Achats & Stock',
        'finances' => 'Finances',
        'rh' => 'RH',
        'system' => 'Système',
    ],

    /*
    | module_family: when set, only one module in this family can be enabled per tenant (e.g. sales vs sales-restaurant).
    | tenant_types: optional; list of tenant types this module is suggested for (empty = all). Used for defaults and UI.
    */

    'users' => [
        'core' => true,
        'label' => 'Utilisateurs',
        'description' => 'Utilisateurs, rôles et permissions du tenant.',
        'route_name' => 'tenant.users.index',
        'lifecycle_handler' => \InovCom\Users\UsersModule::class,
        'enabled_by_default' => true,
        'group' => 'system',
        'icon' => 'identification',
        'permission' => 'users.view',
        'tenant_types' => [],
    ],
    'items' => [
        'core' => false,
        'label' => 'Articles',
        'description' => 'Catalogue produits commerce / POS (hors pharmacie).',
        'route_name' => 'tenant.items.index',
        'lifecycle_handler' => \InovCom\Items\ItemsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-items-migrations',
        'group' => 'catalogue',
        'icon' => 'package',
        'permission' => 'items.view',
        'module_family' => 'catalog',
        'tenant_types' => ['erp'],
        'enabled_when_modules' => ['medicaments'],
        'sidebar' => false,
    ],
    'medicaments' => [
        'core' => false,
        'label' => 'Médicaments',
        'description' => 'Catalogue pharmacie : DCI, forme, dosage, ordonnance, lots / péremption.',
        'route_name' => 'tenant.items.index',
        'lifecycle_handler' => \InovCom\Items\MedicamentsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-items-migrations',
        'group' => 'pharmacy',
        'sidebar_order' => 10,
        'icon' => 'beaker',
        'permission' => 'items.view',
        'module_family' => 'catalog',
        'tenant_types' => ['pharma'],
    ],
    'clients' => [
        'core' => false,
        'label' => 'Clients',
        'description' => 'Gestion des clients, segments, limites de crédit, adresses et contacts.',
        'route_name' => 'tenant.clients.index',
        'lifecycle_handler' => \InovCom\Clients\ClientsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-clients-migrations',
        'group' => 'ventes',
        'sidebar_order' => 20,
        'icon' => 'users',
        'permission' => 'clients.view',
        'tenant_types' => [],
    ],
    'providers' => [
        'core' => false,
        'label' => 'Fournisseurs',
        'description' => 'Gestion des fournisseurs, conditions de paiement et contacts.',
        'route_name' => 'tenant.providers.index',
        'lifecycle_handler' => \InovCom\Providers\ProvidersModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-providers-migrations',
        'group' => 'achats_stock',
        'icon' => 'truck',
        'permission' => 'providers.view',
        'tenant_types' => [],
    ],
    'sales' => [
        'core' => false,
        'label' => 'Ventes',
        'description' => 'Point de vente pharmacie : scanner, ordonnances, remises, paiements.',
        'route_name' => 'tenant.sales.index',
        'lifecycle_handler' => \InovCom\Sales\SalesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-sales-migrations',
        'group' => 'ventes',
        'sidebar_order' => 70,
        'icon' => 'shopping-cart',
        'permission' => 'sales.view',
        'module_family' => 'sales',
        'tenant_types' => ['erp', 'pharma'],
    ],
    'stock' => [
        'core' => false,
        'label' => 'Stock',
        'description' => 'Gestion des stocks, niveaux et ajustements.',
        'route_name' => 'tenant.stock.index',
        'lifecycle_handler' => \InovCom\Stock\StockModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-stock-migrations',
        'group' => 'achats_stock',
        'icon' => 'archive',
        'permission' => 'stock.view',
        'tenant_types' => [],
    ],
    'purchases' => [
        'core' => false,
        'label' => 'Achats',
        'description' => 'Commandes d\'achat et réception de marchandises.',
        'route_name' => 'tenant.purchases.index',
        'lifecycle_handler' => \InovCom\Purchases\PurchasesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-purchases-migrations',
        'group' => 'achats_stock',
        'icon' => 'shopping-bag',
        'permission' => 'purchases.view',
        'tenant_types' => [],
    ],
    'foreign_purchases' => [
        'core' => false,
        'label' => 'Achats étrangers',
        'description' => 'Commandes d\'achat en devises étrangères avec conversion FCFA.',
        'route_name' => 'tenant.foreign_purchases.index',
        'lifecycle_handler' => \InovCom\Purchases\ForeignPurchasesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-purchases-migrations',
        'requires' => ['purchases'],
        'group' => 'achats_stock',
        'icon' => 'globe',
        'permission' => 'foreign_purchases.view',
        'tenant_types' => [],
    ],
    'inventory' => [
        'core' => false,
        'label' => 'Inventaire',
        'description' => 'Comptages de stock et ajustements, même lorsque le magasin est ouvert.',
        'route_name' => 'tenant.inventory.index',
        'lifecycle_handler' => \InovCom\Inventory\InventoryModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-inventory-migrations',
        'group' => 'achats_stock',
        'icon' => 'clipboard-check',
        'permission' => 'inventory.view',
    ],
    'expenses' => [
        'core' => false,
        'label' => 'Dépenses',
        'description' => 'Gestion des dépenses, catégories et workflow d\'approbation.',
        'route_name' => 'tenant.expenses.index',
        'lifecycle_handler' => \InovCom\Expenses\ExpensesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-expenses-migrations',
        'group' => 'finances',
        'icon' => 'banknotes',
        'permission' => 'expenses.view',
        'tenant_types' => [],
    ],
    'caisse' => [
        'core' => false,
        'label' => 'Caisse',
        'description' => 'Caisse physique : ouverture/clôture de session, mouvements manuels, états PDF et Excel.',
        'route_name' => 'tenant.caisse.index',
        'lifecycle_handler' => \InovCom\Caisse\CaisseModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-caisse-migrations',
        'group' => 'finances',
        'icon' => 'calculator',
        'permission' => 'caisse.view',
        'tenant_types' => [],
    ],
    'losses' => [
        'core' => false,
        'label' => 'Pertes',
        'description' => 'Enregistrement des pertes (endommagé, expiré, vol…) et mise à jour du stock.',
        'route_name' => 'tenant.losses.index',
        'lifecycle_handler' => \InovCom\Losses\LossesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-losses-migrations',
        'group' => 'achats_stock',
        'icon' => 'trending-down',
        'permission' => 'losses.view',
        'tenant_types' => [],
    ],
    'debts' => [
        'core' => false,
        'label' => 'Dettes',
        'description' => 'Gestion des dettes clients, paiements et échéanciers.',
        'route_name' => 'tenant.debts.index',
        'lifecycle_handler' => \InovCom\Debts\DebtsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-debts-migrations',
        'group' => 'ventes',
        'sidebar_order' => 90,
        'icon' => 'scale',
        'permission' => 'debts.view',
    ],
    'quotations' => [
        'core' => false,
        'label' => 'Devis',
        'description' => 'Propositions commerciales : brouillon, validation, suspension ou rejet.',
        'route_name' => 'tenant.quotations.index',
        'lifecycle_handler' => \InovCom\Quotations\QuotationsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-quotations-migrations',
        'group' => 'ventes',
        'sidebar_order' => 30,
        'icon' => 'document-text',
        'permission' => 'quotations.view',
        'tenant_types' => [],
    ],
    'reservations' => [
        'core' => false,
        'label' => 'Réservations',
        'description' => 'Réserver des produits pour un client — stock bloqué, conversion en devis.',
        'route_name' => 'tenant.reservations.index',
        'lifecycle_handler' => \InovCom\Reservations\ReservationsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-reservations-migrations',
        'group' => 'ventes',
        'sidebar_order' => 60,
        'icon' => 'bookmark',
        'permission' => 'reservations.view',
        'tenant_types' => [],
    ],
    'prospects' => [
        'core' => false,
        'label' => 'Prospects',
        'description' => 'Prospection commerciale : leads, suivi, conversion en client.',
        'route_name' => 'tenant.prospects.index',
        'lifecycle_handler' => \InovCom\Prospects\ProspectsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-prospects-migrations',
        'group' => 'ventes',
        'sidebar_order' => 10,
        'icon' => 'user-plus',
        'permission' => 'prospects.view',
        'permission_any' => ['crm.prospects.view', 'crm.view'],
        'enabled_when_modules' => ['crm'],
        'requires' => ['clients'],
        'hide_when_modules' => ['crm'],
        'tenant_types' => [],
    ],
    'crm' => [
        'core' => false,
        'label' => 'CRM',
        'description' => 'Relation client boutique : KPI, prospects, pipeline d’opportunités et activités. La conversion crée un client dans le module Clients.',
        'route_name' => null,
        'menu_only' => true,
        'lifecycle_handler' => \InovCom\Crm\CrmModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-crm-suite-migrations',
        'group' => 'ventes',
        'sidebar_order' => 5,
        'icon' => 'users',
        'permission' => 'crm.view',
        'permission_any' => [
            'crm.prospects.view',
            'crm.opportunities.view',
            'crm.activities.view',
            'prospects.view',
        ],
        'requires' => ['clients', 'prospects'],
        'sidebar_children' => [
            [
                'key' => 'crm.kpi',
                'label' => 'KPI',
                'route' => 'tenant.crm.kpi',
                'icon' => 'chart-bar',
                'permission' => 'crm.view',
                'permission_any' => ['crm.prospects.view', 'crm.opportunities.view', 'prospects.view'],
            ],
            [
                'key' => 'crm.prospects',
                'label' => 'Prospects',
                'route' => 'tenant.prospects.index',
                'icon' => 'user-plus',
                'permission' => 'crm.prospects.view',
                'permission_any' => ['prospects.view', 'crm.view'],
            ],
            [
                'key' => 'crm.opportunities',
                'label' => 'Opportunités',
                'route' => 'tenant.crm.opportunities',
                'icon' => 'briefcase',
                'permission' => 'crm.opportunities.view',
                'permission_any' => ['crm.view', 'prospects.view'],
            ],
            [
                'key' => 'crm.activities',
                'label' => 'Activités',
                'route' => 'tenant.crm.activities',
                'icon' => 'clipboard-check',
                'permission' => 'crm.activities.view',
                'permission_any' => ['crm.view', 'prospects.view'],
            ],
        ],
        'tenant_types' => [],
    ],
    'invoicing' => [
        'core' => false,
        'label' => 'Facturation',
        'description' => 'Factures avec ou sans déclaration, numérotation séquentielle par type.',
        'route_name' => 'tenant.invoicing.index',
        'lifecycle_handler' => \InovCom\Invoicing\InvoicingModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-invoicing-migrations',
        'group' => 'ventes',
        'sidebar_order' => 40,
        'icon' => 'receipt',
        'permission' => 'invoicing.view',
        'tenant_types' => [],
    ],
    'invoice_payments' => [
        'core' => false,
        'label' => 'Paiements factures',
        'description' => 'Suivi et encaissement des paiements sur factures émises.',
        'route_name' => 'tenant.invoice_payments.index',
        'lifecycle_handler' => \InovCom\InvoicePayments\InvoicePaymentsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-invoice-payments-migrations',
        'group' => 'ventes',
        'sidebar_order' => 50,
        'icon' => 'credit-card',
        'permission' => 'invoice_payments.view',
        'tenant_types' => [],
    ],
    'returns' => [
        'core' => false,
        'label' => 'Retours & Avoirs',
        'description' => 'Retours clients, avoirs, remboursements, crédits clients et échanges, avec impact stock/créances/trésorerie.',
        'route_name' => 'tenant.returns.index',
        'lifecycle_handler' => \InovCom\Returns\ReturnsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-returns-migrations',
        'group' => 'ventes',
        'sidebar_order' => 80,
        'icon' => 'arrow-uturn-left',
        'permission' => 'returns.view',
        'tenant_types' => [],
    ],
    'reporting' => [
        'core' => false,
        'label' => 'Rapports',
        'description' => 'Rapports et analyses (CA, dépenses, pertes, bénéfice, top produits).',
        'route_name' => 'tenant.reporting.index',
        'lifecycle_handler' => \InovCom\Reporting\ReportingModule::class,
        'enabled_by_default' => false,
        'group' => 'finances',
        'icon' => 'chart-bar',
        'permission' => 'reporting.view',
        'tenant_types' => [],
    ],
    'pharma_reporting' => [
        'core' => false,
        'label' => 'Rapport Pharmacie',
        'description' => 'Tableau de bord, analyse des ventes, rentabilité, stock, achats, finance et alertes.',
        'route_name' => 'tenant.pharma-reporting.dashboard',
        'lifecycle_handler' => \Pharma\Modules\PharmaReportingModule::class,
        'enabled_by_default' => true,
        'group' => 'finances',
        'sidebar_order' => 90,
        'icon' => 'chart-bar',
        'permission' => 'reporting.view',
        'permission_any' => ['reporting.view', 'pharma.view'],
        'tenant_types' => ['pharma'],
    ],
    'payroll' => [
        'core' => false,
        'label' => 'Paie',
        'description' => 'Paie des employés, fiches de paie et périodes.',
        'route_name' => 'tenant.payroll.index',
        'lifecycle_handler' => \InovCom\Payroll\PayrollModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-payroll-migrations',
        'group' => 'rh',
        'icon' => 'briefcase',
        'permission' => 'payroll.view',
    ],
    'attendance' => [
        'core' => false,
        'label' => 'Présence',
        'description' => 'Pointage des employés et fiches de présence avec indicateur de performance.',
        'route_name' => 'tenant.attendance.index',
        'lifecycle_handler' => \InovCom\Attendance\AttendanceModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-attendance-migrations',
        'group' => 'rh',
        'icon' => 'clock',
        'permission' => 'attendance.view',
        'permission_any' => ['attendance.view', 'attendance.view_all', 'attendance.settings'],
        'tenant_types' => [],
    ],
    'tickets' => [
        'core' => false,
        'label' => 'Tickets',
        'description' => 'Suivi des incidents : ouverture, itérations, résolution et clôture.',
        'route_name' => 'tenant.tickets.index',
        'lifecycle_handler' => \InovCom\Tickets\TicketsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-tickets-migrations',
        'group' => 'system',
        'icon' => 'ticket',
        'permission' => 'tickets.view',
        'tenant_types' => [],
    ],
    'configuration' => [
        'core' => true,
        'label' => 'Configuration',
        'description' => 'Paramètres système, nom du magasin et message de personnalisation (bienvenue).',
        'route_name' => 'tenant.configuration.index',
        'lifecycle_handler' => \InovCom\Configuration\ConfigurationModule::class,
        'enabled_by_default' => true,
        'group' => 'system',
        'icon' => 'cog',
        'permission' => 'configuration.view',
        'tenant_types' => [],
    ],
    'pharma' => [
        'core' => false,
        'label' => 'Hub Pharmacie',
        'description' => 'Point d’entrée Bproo Pharma : rôles pharmacie et accès rapide aux modules métier.',
        'route_name' => 'tenant.pharma.hub',
        'lifecycle_handler' => \Pharma\Modules\PharmaModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-pharma-migrations',
        'group' => 'pharmacy',
        'sidebar_order' => 1,
        'icon' => 'beaker',
        'permission' => 'pharma.view',
        'tenant_types' => ['pharma'],
    ],
    'batches' => [
        'core' => false,
        'label' => 'Lots / Péremption',
        'description' => 'Suivi des lots et dates de péremption (pharmacie).',
        'route_name' => 'tenant.batches.index',
        'lifecycle_handler' => \InovCom\Batches\BatchesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-batches-migrations',
        'group' => 'pharmacy',
        'icon' => 'calendar',
        'permission' => 'batches.view',
        'tenant_types' => ['erp', 'pharma'],
    ],
    'prescriptions' => [
        'core' => false,
        'label' => 'Ordonnances',
        'description' => 'Ordonnances et dispensation (pharmacie).',
        'route_name' => 'tenant.prescriptions.index',
        'lifecycle_handler' => \InovCom\Prescriptions\PrescriptionsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-prescriptions-migrations',
        'group' => 'pharmacy',
        'icon' => 'clipboard-check',
        'permission' => 'prescriptions.view',
        'tenant_types' => ['erp', 'pharma'],
    ],
];
