<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Core vs normal modules
    |--------------------------------------------------------------------------
    | Core modules (users, configuration) are always available per tenant.
    | Normal modules (items, etc.) are optional; enable per tenant as needed.
    | Only core module migrations are run during tenant provisioning.
    */
    'core_migration_tags' => [
        'inovcom-users-migrations',
    ],

    'sidebar_groups' => [
        'school_scolarite' => 'Scolarité',
        'school_finances' => 'Finances scolaires',
        'school_examens' => 'Examens & résultats',
        'school_referentiel' => 'Référentiel',
        'school_admin' => 'Administration',
        'pressing' => 'Pressing',
        'catalogue' => 'Catalogue',
        'ventes' => 'Ventes',
        'pharmacy' => 'Pharmacie',
        'achats_stock' => 'Achats & Stock',
        'finances' => 'Finances',
        'rh' => 'RH',
        'system' => 'Système',
    ],

    /*
    | module_family: when set, only one module in this family can be enabled per tenant (e.g. sales vs sales-restaurant).
    | tenant_types: optional; list of tenant types this module is suggested for (empty = all). Used for defaults and UI.
    */

    'users' => [
        'core' => true,
        'label' => 'Utilisateurs',
        'description' => 'Utilisateurs, rôles et permissions du tenant.',
        'route_name' => 'tenant.users.index',
        'lifecycle_handler' => \InovCom\Users\UsersModule::class,
        'enabled_by_default' => true,
        'group' => 'system',
        'icon' => 'identification',
        'permission' => 'users.view',
        'tenant_types' => [],
    ],
    'items' => [
        'core' => false,
        'label' => 'Articles',
        'description' => 'Catalogue produits commerce / POS : unités, tarifs et codes-barres.',
        'route_name' => 'tenant.items.index',
        'lifecycle_handler' => \InovCom\Items\ItemsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-items-migrations',
        'group' => 'catalogue',
        'icon' => 'package',
        'permission' => 'items.view',
        'module_family' => 'catalog',
        'tenant_types' => ['erp'],
        'enabled_when_modules' => ['medicaments'],
    ],
    'medicaments' => [
        'core' => false,
        'label' => 'Médicaments',
        'description' => 'Catalogue pharmacie : DCI, forme, dosage, ordonnance, lots / péremption.',
        'route_name' => 'tenant.items.index',
        'lifecycle_handler' => \InovCom\Items\MedicamentsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'inovcom-items-migrations',
        'group' => 'pharmacy',
        'icon' => 'beaker',
        'permission' => 'items.view',
        'module_family' => 'catalog',
        'tenant_types' => ['pharma'],
    ],
    'clients' => [
        'core' => false,
        'label' => 'Clients',
        'description' => 'Gestion des clients, segments, limites de crédit, adresses et contacts.',
        'route_name' => 'tenant.clients.index',
        'lifecycle_handler' => \InovCom\Clients\ClientsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-clients-migrations',
        'group' => 'ventes',
        'sidebar_order' => 20,
        'icon' => 'users',
        'permission' => 'clients.view',
        'tenant_types' => [],
    ],
    'providers' => [
        'core' => false,
        'label' => 'Fournisseurs',
        'description' => 'Gestion des fournisseurs, conditions de paiement et contacts.',
        'route_name' => 'tenant.providers.index',
        'lifecycle_handler' => \InovCom\Providers\ProvidersModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-providers-migrations',
        'group' => 'achats_stock',
        'icon' => 'truck',
        'permission' => 'providers.view',
        'tenant_types' => [],
    ],
    'sales' => [
        'core' => false,
        'label' => 'Ventes',
        'description' => 'Point de vente, gestion des ventes (détail, semi-gros, gros).',
        'route_name' => 'tenant.sales.index',
        'lifecycle_handler' => \InovCom\Sales\SalesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-sales-migrations',
        'group' => 'ventes',
        'sidebar_order' => 70,
        'icon' => 'shopping-cart',
        'permission' => 'sales.view',
        'module_family' => 'sales',
        'tenant_types' => ['erp', 'pharma'],
    ],
    'stock' => [
        'core' => false,
        'label' => 'Stock',
        'description' => 'Gestion des stocks, niveaux et ajustements.',
        'route_name' => 'tenant.stock.index',
        'lifecycle_handler' => \InovCom\Stock\StockModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-stock-migrations',
        'group' => 'achats_stock',
        'icon' => 'archive',
        'permission' => 'stock.view',
        'tenant_types' => [],
    ],
    'purchases' => [
        'core' => false,
        'label' => 'Achats',
        'description' => 'Commandes d\'achat et réception de marchandises.',
        'route_name' => 'tenant.purchases.index',
        'lifecycle_handler' => \InovCom\Purchases\PurchasesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-purchases-migrations',
        'group' => 'achats_stock',
        'icon' => 'shopping-bag',
        'permission' => 'purchases.view',
        'tenant_types' => [],
    ],
    'foreign_purchases' => [
        'core' => false,
        'label' => 'Achats étrangers',
        'description' => 'Commandes d\'achat en devises étrangères avec conversion FCFA.',
        'route_name' => 'tenant.foreign_purchases.index',
        'lifecycle_handler' => \InovCom\Purchases\ForeignPurchasesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-purchases-migrations',
        'requires' => ['purchases'],
        'group' => 'achats_stock',
        'icon' => 'globe',
        'permission' => 'foreign_purchases.view',
        'tenant_types' => [],
    ],
    'inventory' => [
        'core' => false,
        'label' => 'Inventaire',
        'description' => 'Comptages de stock et ajustements, même lorsque le magasin est ouvert.',
        'route_name' => 'tenant.inventory.index',
        'lifecycle_handler' => \InovCom\Inventory\InventoryModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-inventory-migrations',
        'group' => 'achats_stock',
        'icon' => 'clipboard-check',
        'permission' => 'inventory.view',
    ],
    'expenses' => [
        'core' => false,
        'label' => 'Dépenses',
        'description' => 'Gestion des dépenses, catégories et workflow d\'approbation.',
        'route_name' => 'tenant.expenses.index',
        'lifecycle_handler' => \InovCom\Expenses\ExpensesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-expenses-migrations',
        'group' => 'finances',
        'icon' => 'banknotes',
        'permission' => 'expenses.view',
        'tenant_types' => [],
    ],
    'caisse' => [
        'core' => false,
        'label' => 'Caisse',
        'description' => 'Caisse physique : ouverture/clôture de session, mouvements manuels, états PDF et Excel.',
        'route_name' => 'tenant.caisse.index',
        'lifecycle_handler' => \InovCom\Caisse\CaisseModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-caisse-migrations',
        'group' => 'finances',
        'icon' => 'calculator',
        'permission' => 'caisse.view',
        'tenant_types' => [],
    ],
    'losses' => [
        'core' => false,
        'label' => 'Pertes',
        'description' => 'Enregistrement des pertes (endommagé, expiré, vol…) et mise à jour du stock.',
        'route_name' => 'tenant.losses.index',
        'lifecycle_handler' => \InovCom\Losses\LossesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-losses-migrations',
        'group' => 'achats_stock',
        'icon' => 'trending-down',
        'permission' => 'losses.view',
        'tenant_types' => [],
    ],
    'debts' => [
        'core' => false,
        'label' => 'Dettes',
        'description' => 'Gestion des dettes clients, paiements et échéanciers.',
        'route_name' => 'tenant.debts.index',
        'lifecycle_handler' => \InovCom\Debts\DebtsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-debts-migrations',
        'group' => 'ventes',
        'sidebar_order' => 90,
        'icon' => 'scale',
        'permission' => 'debts.view',
    ],
    'quotations' => [
        'core' => false,
        'label' => 'Devis',
        'description' => 'Propositions commerciales : brouillon, validation, suspension ou rejet.',
        'route_name' => 'tenant.quotations.index',
        'lifecycle_handler' => \InovCom\Quotations\QuotationsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-quotations-migrations',
        'group' => 'ventes',
        'sidebar_order' => 30,
        'icon' => 'document-text',
        'permission' => 'quotations.view',
        'tenant_types' => [],
    ],
    'reservations' => [
        'core' => false,
        'label' => 'Réservations',
        'description' => 'Réserver des produits pour un client — stock bloqué, conversion en devis.',
        'route_name' => 'tenant.reservations.index',
        'lifecycle_handler' => \InovCom\Reservations\ReservationsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-reservations-migrations',
        'group' => 'ventes',
        'sidebar_order' => 60,
        'icon' => 'bookmark',
        'permission' => 'reservations.view',
        'tenant_types' => [],
    ],
    'prospects' => [
        'core' => false,
        'label' => 'Prospects',
        'description' => 'Prospection commerciale : leads, suivi, conversion en client.',
        'route_name' => 'tenant.prospects.index',
        'lifecycle_handler' => \InovCom\Prospects\ProspectsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-prospects-migrations',
        'group' => 'ventes',
        'sidebar_order' => 10,
        'icon' => 'user-plus',
        'permission' => 'prospects.view',
        'permission_any' => ['crm.prospects.view', 'crm.view'],
        'enabled_when_modules' => ['crm'],
        'requires' => ['clients'],
        'hide_when_modules' => ['crm'],
        'tenant_types' => [],
    ],
    'crm' => [
        'core' => false,
        'label' => 'CRM',
        'description' => 'Relation client boutique : KPI, prospects, pipeline d’opportunités et activités. La conversion crée un client dans le module Clients.',
        'route_name' => null,
        'menu_only' => true,
        'lifecycle_handler' => \InovCom\Crm\CrmModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-crm-suite-migrations',
        'group' => 'ventes',
        'sidebar_order' => 5,
        'icon' => 'users',
        'permission' => 'crm.view',
        'permission_any' => [
            'crm.prospects.view',
            'crm.opportunities.view',
            'crm.activities.view',
            'prospects.view',
        ],
        'requires' => ['clients', 'prospects'],
        'sidebar_children' => [
            [
                'key' => 'crm.kpi',
                'label' => 'Tableau de bord',
                'route' => 'tenant.crm.kpi',
                'icon' => 'chart-bar',
                'permission' => 'crm.view',
                'permission_any' => ['crm.prospects.view', 'crm.opportunities.view', 'prospects.view'],
            ],
            [
                'key' => 'crm.prospects',
                'label' => 'Prospects',
                'route' => 'tenant.prospects.index',
                'icon' => 'user-plus',
                'permission' => 'crm.prospects.view',
                'permission_any' => ['prospects.view', 'crm.view'],
            ],
            [
                'key' => 'crm.opportunities',
                'label' => 'Opportunités',
                'route' => 'tenant.crm.opportunities',
                'icon' => 'briefcase',
                'permission' => 'crm.opportunities.view',
                'permission_any' => ['crm.view', 'prospects.view'],
            ],
            [
                'key' => 'crm.activities',
                'label' => 'Activités',
                'route' => 'tenant.crm.activities',
                'icon' => 'clipboard-check',
                'permission' => 'crm.activities.view',
                'permission_any' => ['crm.view', 'prospects.view'],
            ],
            [
                'key' => 'crm.clients',
                'label' => 'Clients',
                'route' => 'tenant.crm.clients',
                'icon' => 'users',
                'permission' => 'crm.view',
                'permission_any' => ['clients.view', 'crm.prospects.view'],
            ],
        ],
        'tenant_types' => [],
    ],
    'invoicing' => [
        'core' => false,
        'label' => 'Facturation',
        'description' => 'Factures avec ou sans déclaration, numérotation séquentielle par type.',
        'route_name' => 'tenant.invoicing.index',
        'lifecycle_handler' => \InovCom\Invoicing\InvoicingModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-invoicing-migrations',
        'group' => 'ventes',
        'sidebar_order' => 40,
        'icon' => 'receipt',
        'permission' => 'invoicing.view',
        'tenant_types' => [],
    ],
    'invoice_payments' => [
        'core' => false,
        'label' => 'Paiements factures',
        'description' => 'Suivi et encaissement des paiements sur factures émises.',
        'route_name' => 'tenant.invoice_payments.index',
        'lifecycle_handler' => \InovCom\InvoicePayments\InvoicePaymentsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-invoice-payments-migrations',
        'group' => 'ventes',
        'sidebar_order' => 50,
        'icon' => 'credit-card',
        'permission' => 'invoice_payments.view',
        'tenant_types' => [],
    ],
    'returns' => [
        'core' => false,
        'label' => 'Retours & Avoirs',
        'description' => 'Retours clients, avoirs, remboursements, crédits clients et échanges, avec impact stock/créances/trésorerie.',
        'route_name' => 'tenant.returns.index',
        'lifecycle_handler' => \InovCom\Returns\ReturnsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-returns-migrations',
        'group' => 'ventes',
        'sidebar_order' => 80,
        'icon' => 'arrow-uturn-left',
        'permission' => 'returns.view',
        'tenant_types' => [],
    ],
    'reporting' => [
        'core' => false,
        'label' => 'Rapports',
        'description' => 'Rapports et analyses (CA, dépenses, pertes, bénéfice, top produits).',
        'route_name' => 'tenant.reporting.index',
        'lifecycle_handler' => \InovCom\Reporting\ReportingModule::class,
        'enabled_by_default' => false,
        'group' => 'finances',
        'icon' => 'chart-bar',
        'permission' => 'reporting.view',
        'tenant_types' => [],
    ],
    'pharma_reporting' => [
        'core' => false,
        'label' => 'Rapport Pharmacie',
        'description' => 'Tableau de bord, analyse des ventes, rentabilité, stock, achats, finance et alertes.',
        'route_name' => 'tenant.pharma-reporting.dashboard',
        'lifecycle_handler' => \Pharma\Modules\PharmaReportingModule::class,
        'enabled_by_default' => true,
        'group' => 'finances',
        'sidebar_order' => 90,
        'icon' => 'chart-bar',
        'permission' => 'reporting.view',
        'permission_any' => ['reporting.view', 'pharma.view'],
        'tenant_types' => ['pharma'],
    ],
    'payroll' => [
        'core' => false,
        'label' => 'Paie',
        'description' => 'Paie des employés, fiches de paie et périodes.',
        'route_name' => 'tenant.payroll.index',
        'lifecycle_handler' => \InovCom\Payroll\PayrollModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-payroll-migrations',
        'group' => 'rh',
        'icon' => 'briefcase',
        'permission' => 'payroll.view',
    ],
    'attendance' => [
        'core' => false,
        'label' => 'Présence',
        'description' => 'Pointage des employés et fiches de présence avec indicateur de performance.',
        'route_name' => 'tenant.attendance.index',
        'lifecycle_handler' => \InovCom\Attendance\AttendanceModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-attendance-migrations',
        'group' => 'rh',
        'icon' => 'clock',
        'permission' => 'attendance.view',
        'permission_any' => ['attendance.view', 'attendance.view_all', 'attendance.settings'],
        'tenant_types' => [],
    ],
    'tickets' => [
        'core' => false,
        'label' => 'Tickets',
        'description' => 'Suivi des incidents : ouverture, itérations, résolution et clôture.',
        'route_name' => 'tenant.tickets.index',
        'lifecycle_handler' => \InovCom\Tickets\TicketsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-tickets-migrations',
        'group' => 'system',
        'icon' => 'ticket',
        'permission' => 'tickets.view',
        'tenant_types' => [],
    ],
    'configuration' => [
        'core' => true,
        'label' => 'Configuration',
        'description' => 'Paramètres système, nom du magasin et message de personnalisation (bienvenue).',
        'route_name' => 'tenant.configuration.index',
        'lifecycle_handler' => \InovCom\Configuration\ConfigurationModule::class,
        'enabled_by_default' => true,
        'group' => 'system',
        'icon' => 'cog',
        'permission' => 'configuration.view',
        'tenant_types' => [],
    ],
    'batches' => [
        'core' => false,
        'label' => 'Lots / Péremption',
        'description' => 'Suivi des lots et dates de péremption (pharmacie).',
        'route_name' => 'tenant.batches.index',
        'lifecycle_handler' => \InovCom\Batches\BatchesModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-batches-migrations',
        'group' => 'pharmacy',
        'icon' => 'calendar',
        'permission' => 'batches.view',
        'tenant_types' => ['erp', 'pharma'],
    ],
    'prescriptions' => [
        'core' => false,
        'label' => 'Ordonnances',
        'description' => 'Ordonnances et dispensation (pharmacie).',
        'route_name' => 'tenant.prescriptions.index',
        'lifecycle_handler' => \InovCom\Prescriptions\PrescriptionsModule::class,
        'enabled_by_default' => false,
        'migration_tag' => 'inovcom-prescriptions-migrations',
        'group' => 'pharmacy',
        'icon' => 'beaker',
        'permission' => 'prescriptions.view',
        'tenant_types' => ['erp', 'pharma'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Pressing modules (managed from Control Center for pressing tenants)
    |--------------------------------------------------------------------------
    */
    'agences' => [
        'core' => false,
        'label' => 'Agences',
        'description' => 'Multi-agences pressing : création, responsables et rattachement des données.',
        'route_name' => 'tenant.agences.index',
        'lifecycle_handler' => \Pressing\Modules\AgencesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'pressing-migrations',
        'group' => 'system',
        'sidebar_order' => 15,
        'icon' => 'building-office',
        'permission' => 'agences.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_clients' => [
        'core' => false,
        'label' => 'Nos Clients',
        'description' => 'Clients du pressing (WhatsApp, recherche multi-agences, historique commandes).',
        'route_name' => 'tenant.pressing_clients.index',
        'lifecycle_handler' => \Pressing\Modules\PressingClientsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'pressing-migrations',
        'requires' => ['agences'],
        'group' => 'pressing',
        'sidebar_order' => 20,
        'icon' => 'users',
        'permission' => 'pressing_clients.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_lavage_relances' => [
        'core' => false,
        'label' => 'Relances dépôt lavage',
        'description' => 'Lister les clients sans dépôts lavage sur une période donnée, puis imprimer et relancer.',
        'route_name' => 'tenant.pressing_lavage_relances.index',
        'lifecycle_handler' => \Pressing\Modules\PressingLavageRelancesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => null,
        'requires' => ['pressing_clients', 'pressing_orders'],
        'group' => 'pressing',
        'sidebar_order' => 25,
        'icon' => 'user-group',
        'permission' => 'pressing_lavage_relances.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_orders' => [
        'core' => false,
        'label' => 'Réception',
        'description' => 'Réception, commandes multi-articles, tarification et paiements.',
        'route_name' => 'tenant.pressing_orders.index',
        'lifecycle_handler' => \Pressing\Modules\PressingOrdersModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'pressing-migrations',
        'requires' => ['agences', 'pressing_clients'],
        'group' => 'pressing',
        'sidebar_order' => 30,
        'icon' => 'clipboard-document-list',
        'permission' => 'pressing_orders.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_workflow' => [
        'core' => false,
        'label' => 'Production',
        'description' => 'Kanban production : Mise en Production → Lavage → Séchage → Repassage → Fin de production.',
        'route_name' => 'tenant.pressing_workflow.index',
        'lifecycle_handler' => \Pressing\Modules\PressingWorkflowModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'pressing-migrations',
        'requires' => ['pressing_orders'],
        'group' => 'pressing',
        'sidebar_order' => 40,
        'icon' => 'view-columns',
        'permission' => 'pressing_workflow.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_fin_production' => [
        'core' => false,
        'label' => 'Fin de production',
        'description' => 'Contrôle qualité, emballage et mise en livraison (agence ou domicile).',
        'route_name' => 'tenant.pressing_fin_production.index',
        'lifecycle_handler' => \Pressing\Modules\PressingFinProductionModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'pressing-migrations',
        'requires' => ['pressing_orders', 'pressing_workflow'],
        'group' => 'pressing',
        'sidebar_order' => 42,
        'icon' => 'clipboard-check',
        'permission' => 'pressing_fin_production.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_settings' => [
        'core' => false,
        'label' => 'Paramétrage',
        'description' => 'Types, tarifs, workflow, délais, taxes, messages, paiements, agences et employés.',
        'route_name' => 'tenant.pressing_settings.index',
        'lifecycle_handler' => \Pressing\Modules\PressingSettingsModule::class,
        'enabled_by_default' => true,
        'requires' => ['agences'],
        'group' => 'system',
        'sidebar_order' => 20,
        'icon' => 'cog-6-tooth',
        'permission' => 'pressing_settings.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_deliveries' => [
        'core' => false,
        'label' => 'Livraisons',
        'description' => 'Livraison agence ou domicile, chauffeur, suivi et confirmation.',
        'route_name' => 'tenant.pressing_deliveries.index',
        'lifecycle_handler' => \Pressing\Modules\PressingDeliveriesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'pressing-migrations',
        'requires' => ['pressing_orders'],
        'group' => 'pressing',
        'sidebar_order' => 44,
        'icon' => 'truck',
        'permission' => 'pressing_deliveries.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_reports' => [
        'core' => false,
        'label' => 'Rapports et analyses',
        'description' => 'Rapports commandes / encaissements avec export CSV.',
        'route_name' => 'tenant.pressing_reports.index',
        'lifecycle_handler' => null,
        'enabled_by_default' => true,
        'requires' => ['pressing_orders'],
        'group' => 'pressing',
        'sidebar_order' => 45,
        'icon' => 'chart-bar',
        'permission' => 'pressing_settings.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_consumables' => [
        'core' => false,
        'label' => 'Bons de sortie',
        'description' => 'Bons de sortie atelier (lessive, savon…) — le stock se gère dans Stock.',
        'route_name' => 'tenant.pressing_consumables.index',
        'lifecycle_handler' => \Pressing\Modules\PressingConsumablesModule::class,
        'enabled_by_default' => true,
        'requires' => ['items', 'stock'],
        'group' => 'pressing',
        'sidebar_order' => 46,
        'icon' => 'beaker',
        'permission' => 'pressing_consumables.view',
        'tenant_types' => ['pressing'],
    ],
    'pressing_loyalty' => [
        'core' => false,
        'label' => 'Fidélité',
        'description' => 'Programme de points client et récompenses (bons de réduction).',
        'route_name' => 'tenant.pressing_loyalty.index',
        'lifecycle_handler' => \Pressing\Modules\PressingLoyaltyModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'pressing-migrations',
        'requires' => ['pressing_clients', 'pressing_orders'],
        'group' => 'pressing',
        'sidebar_order' => 47,
        'icon' => 'gift',
        'permission' => 'pressing_loyalty.view',
        'tenant_types' => ['pressing'],
    ],

    /*
    |--------------------------------------------------------------------------
    | School modules (managed from Control Center for school tenants)
    |--------------------------------------------------------------------------
    */
    'school' => [
        'core' => false,
        'label' => 'Tableau de bord',
        'description' => 'Vue d’ensemble des modules School activés pour le tenant.',
        'route_name' => 'tenant.dashboard',
        'lifecycle_handler' => \School\Modules\SchoolModule::class,
        'enabled_by_default' => true,
        'group' => 'school_referentiel',
        'sidebar' => false,
        'sidebar_order' => 1,
        'icon' => 'dashboard',
        'permission' => 'school.view',
        'tenant_types' => ['school'],
    ],
    'school_years' => [
        'core' => false,
        'label' => 'Années académiques',
        'description' => 'Année académique centrale : création, réutilisation des entités, clôture.',
        'route_name' => 'tenant.school.years.index',
        'lifecycle_handler' => \School\Modules\SchoolYearsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'group' => 'school_referentiel',
        'sidebar_order' => 10,
        'icon' => 'calendar',
        'permission' => 'school_years.view',
        'tenant_types' => ['school'],
    ],
    'school_classes' => [
        'core' => false,
        'label' => 'Classes',
        'description' => 'Niveaux et classes réutilisables d’une année à l’autre.',
        'route_name' => 'tenant.school.classes.index',
        'lifecycle_handler' => \School\Modules\SchoolClassesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years'],
        'group' => 'school_referentiel',
        'sidebar_order' => 20,
        'icon' => 'bookmark',
        'permission' => 'school_classes.view',
        'tenant_types' => ['school'],
    ],
    'school_subjects' => [
        'core' => false,
        'label' => 'Matières',
        'description' => 'Référentiel des matières (utilisées pour examens, coefficients et bulletins).',
        'route_name' => 'tenant.school.subjects.index',
        'lifecycle_handler' => \School\Modules\SchoolSubjectsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years'],
        'group' => 'school_referentiel',
        'sidebar_order' => 30,
        'icon' => 'document-text',
        'permission' => 'school_subjects.view',
        'tenant_types' => ['school'],
    ],
    'school_teachers' => [
        'core' => false,
        'label' => 'Enseignants',
        'description' => 'Profils enseignants réutilisables par année.',
        'route_name' => 'tenant.school.teachers.index',
        'lifecycle_handler' => \School\Modules\SchoolTeachersModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years'],
        'group' => 'school_scolarite',
        'sidebar_order' => 10,
        'icon' => 'briefcase',
        'permission' => 'school_teachers.view',
        'tenant_types' => ['school'],
    ],
    'school_students' => [
        'core' => false,
        'label' => 'Élèves',
        'description' => 'Profils élèves permanents : identité, parents, historique académique et financier.',
        'route_name' => 'tenant.school.students.index',
        'lifecycle_handler' => \School\Modules\SchoolStudentsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'group' => 'school_scolarite',
        'sidebar_order' => 20,
        'icon' => 'users',
        'permission' => 'school_students.view',
        'tenant_types' => ['school'],
        'sidebar_children' => [
            ['label' => 'Élèves', 'route' => 'tenant.school.students.index'],
            ['label' => 'Parents / Tuteurs', 'route' => 'tenant.school.parents.index'],
        ],
    ],
    'school_documents' => [
        'core' => false,
        'label' => 'Pièces',
        'description' => 'Documents fournis par chaque élève tout au long de son parcours (acte de naissance, pièce d’identité, certificats…).',
        'route_name' => 'tenant.school.documents.index',
        'lifecycle_handler' => \School\Modules\SchoolDocumentsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_students'],
        'group' => 'school_scolarite',
        'sidebar_order' => 22,
        'icon' => 'document-text',
        'permission' => 'school_documents.view',
        'tenant_types' => ['school'],
    ],
    'school_enrollments' => [
        'core' => false,
        'label' => 'Inscriptions',
        'description' => 'Inscription par année académique sans bloquer sur un profil incomplet.',
        'route_name' => 'tenant.school.enrollments.index',
        'lifecycle_handler' => \School\Modules\SchoolEnrollmentsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years', 'school_students', 'school_classes'],
        'group' => 'school_scolarite',
        'sidebar_order' => 30,
        'icon' => 'user-plus',
        'permission' => 'school_enrollments.view',
        'tenant_types' => ['school'],
    ],
    'school_timetable' => [
        'core' => false,
        'label' => 'Planning',
        'description' => 'Attribuer les matières aux enseignants par classe, puis placer les séances dans la grille hebdomadaire.',
        'route_name' => 'tenant.school.timetable.index',
        'lifecycle_handler' => \School\Modules\SchoolTimetableModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years', 'school_classes', 'school_subjects', 'school_teachers'],
        'group' => 'school_scolarite',
        'sidebar_order' => 32,
        'icon' => 'calendar',
        'permission' => 'school_timetable.view',
        'tenant_types' => ['school'],
        'sidebar_children' => [
            ['label' => 'Cours', 'route' => 'tenant.school.courses.index'],
            ['label' => 'Emploi du temps', 'route' => 'tenant.school.timetable.index'],
            ['label' => 'Salles', 'route' => 'tenant.school.rooms.index'],
        ],
    ],
    'school_attendance' => [
        'core' => false,
        'label' => 'Présences',
        'description' => 'Appel par cours selon l’emploi du temps (présent, absent, retard, excusé).',
        'route_name' => 'tenant.school.attendance.index',
        'lifecycle_handler' => \School\Modules\SchoolAttendanceModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years', 'school_students', 'school_classes', 'school_enrollments'],
        'group' => 'school_scolarite',
        'sidebar_order' => 35,
        'icon' => 'clipboard-check',
        'permission' => 'school_attendance.view',
        'tenant_types' => ['school'],
    ],
    'school_id_cards' => [
        'core' => false,
        'label' => 'Cartes ID',
        'description' => 'Cartes élèves unitaire / lot, QR, photo, impression PDF.',
        'route_name' => 'tenant.school.id_cards.index',
        'lifecycle_handler' => \School\Modules\SchoolIdCardsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_students'],
        'group' => 'school_scolarite',
        'sidebar_order' => 40,
        'icon' => 'identification',
        'permission' => 'school_id_cards.view',
        'tenant_types' => ['school'],
    ],
    'school_fees' => [
        'core' => false,
        'label' => 'Structures de frais',
        'description' => 'Barèmes de frais configurables par année et classe.',
        'route_name' => 'tenant.school.fees.index',
        'lifecycle_handler' => \School\Modules\SchoolFeesModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years', 'school_classes'],
        'group' => 'school_finances',
        'sidebar_order' => 10,
        'icon' => 'currency-dollar',
        'permission' => 'school_fees.view',
        'tenant_types' => ['school'],
    ],
    'school_payments' => [
        'core' => false,
        'label' => 'Paiements',
        'description' => 'Paiements banque (vérification) et paiements à l’école + reçus + soldes scolarité.',
        'route_name' => 'tenant.school.payments.index',
        'lifecycle_handler' => \School\Modules\SchoolPaymentsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_students'],
        'group' => 'school_finances',
        'sidebar_order' => 20,
        'icon' => 'banknotes',
        'permission' => 'school_payments.view',
        'tenant_types' => ['school'],
        'sidebar_children' => [
            ['label' => 'Paiements', 'route' => 'tenant.school.payments.index'],
            ['label' => 'Soldes scolarité', 'route' => 'tenant.school.tuition.index'],
        ],
    ],
    'school_exams' => [
        'core' => false,
        'label' => 'Examens',
        'description' => 'Devoirs, interrogations, épreuves de séquence et compositions trimestrielles, avec saisie des notes.',
        'route_name' => 'tenant.school.exams.index',
        'lifecycle_handler' => \School\Modules\SchoolExamsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years', 'school_classes', 'school_subjects', 'school_students', 'school_enrollments'],
        'group' => 'school_examens',
        'sidebar_order' => 10,
        'icon' => 'clipboard-check',
        'permission' => 'school_exams.view',
        'tenant_types' => ['school'],
    ],
    'school_grading' => [
        'core' => false,
        'label' => 'Notation',
        'description' => 'Moteur de calcul configurable : barèmes, coefficients, passage, promotion, classement.',
        'route_name' => 'tenant.school.grading.systems.index',
        'lifecycle_handler' => \School\Modules\SchoolGradingModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_years', 'school_classes', 'school_subjects', 'school_exams'],
        'group' => 'school_examens',
        'sidebar_order' => 20,
        'icon' => 'calculator',
        'permission' => 'school_grading.view',
        'tenant_types' => ['school'],
    ],
    'school_publications' => [
        'core' => false,
        'label' => 'Publication résultats',
        'description' => 'Publication conditionnée : frais, notes validées, approbation directeur.',
        'route_name' => 'tenant.school.publications.index',
        'lifecycle_handler' => \School\Modules\SchoolPublicationsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_exams', 'school_grading', 'school_students'],
        'group' => 'school_examens',
        'sidebar_order' => 30,
        'icon' => 'document-text',
        'permission' => 'school_publications.view',
        'tenant_types' => ['school'],
    ],
    'school_report_cards' => [
        'core' => false,
        'label' => 'Bulletins & relevés',
        'description' => 'Bulletins, relevés académiques et feuilles de notes (aperçu / impression / PDF).',
        'route_name' => 'tenant.school.report_cards.index',
        'lifecycle_handler' => \School\Modules\SchoolReportCardsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_grading', 'school_students', 'school_enrollments'],
        'group' => 'school_examens',
        'sidebar_order' => 40,
        'icon' => 'clipboard-list',
        'permission' => 'school_report_cards.view',
        'tenant_types' => ['school'],
    ],
    'school_notifications' => [
        'core' => false,
        'label' => 'Notifications',
        'description' => 'SMS / Email automatiques : inscriptions, paiements, résultats, bulletins, annonces.',
        'route_name' => 'tenant.school.notifications.index',
        'lifecycle_handler' => \School\Modules\SchoolNotificationsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_students'],
        'group' => 'school_admin',
        'sidebar_order' => 10,
        'icon' => 'bell',
        'permission' => 'school_notifications.view',
        'tenant_types' => ['school'],
    ],
    'school_settings' => [
        'core' => false,
        'label' => 'Paramétrage école',
        'description' => 'Listes configurables, langues et journal d’audit.',
        'route_name' => 'tenant.school.options.index',
        'lifecycle_handler' => \School\Modules\SchoolSettingsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'group' => 'school_admin',
        'sidebar_order' => 20,
        'icon' => 'cog',
        'permission' => 'school_settings.view',
        'tenant_types' => ['school'],
        'sidebar_children' => [
            ['label' => 'Listes', 'route' => 'tenant.school.options.index'],
            ['label' => 'Matricules', 'route' => 'tenant.school.id_settings.index'],
            ['label' => 'Langues', 'route' => 'tenant.school.languages.index'],
            ['label' => 'Audit', 'route' => 'tenant.school.audit.index'],
        ],
    ],
    'school_pilotage' => [
        'core' => false,
        'label' => 'Pilotage',
        'description' => 'Cockpit de direction : effectifs, recouvrement, alertes et suivi opérationnel.',
        'route_name' => 'tenant.school.pilotage.index',
        'lifecycle_handler' => \School\Modules\SchoolPilotageModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_students'],
        'group' => 'school_admin',
        'sidebar_order' => 1,
        'icon' => 'presentation-chart',
        'permission' => 'school_pilotage.view',
        'tenant_types' => ['school'],
    ],
    'school_reports' => [
        'core' => false,
        'label' => 'Rapports',
        'description' => 'Listes académiques, débiteurs, paiements et présences — impression PDF.',
        'route_name' => 'tenant.school.reports.index',
        'lifecycle_handler' => \School\Modules\SchoolReportsModule::class,
        'enabled_by_default' => true,
        'migration_tag' => 'bproo-school-migrations',
        'requires' => ['school_students'],
        'group' => 'school_admin',
        'sidebar_order' => 5,
        'icon' => 'chart-bar',
        'permission' => 'school_reports.view',
        'tenant_types' => ['school'],
    ],
];
