<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Core vs default modules
    |--------------------------------------------------------------------------
    | Core modules (users, configuration, clients) are central per tenant.
    | Client is the centre of the system; other modules depend on it.
    | enabled_by_default: only clients, users, configuration are on for new tenants.
    | Items is optional (not default); enable per tenant if needed.
    | menu_order: lower = earlier in sidebar (Clients first).
    */
    'core_migration_tags' => [
        'inovcom-users-migrations',
        'inovcom-clients-migrations',
        'inovcom-offres-migrations',
        'inovcom-devis-migrations',
        'inovcom-projets-migrations',
        'inovcom-facturation-migrations',
        'inovcom-achats-migrations',
        'inovcom-maintenance-migrations',
        'inovcom-dms-migrations',
        'inovcom-planning-migrations',
        'inovcom-suivi-migrations',
        'inovcom-rh-migrations',
        'inovcom-stock-migrations',
        'inovcom-logistique-migrations',
    ],

    'clients' => [
        'core' => true,
        'label' => 'Clients',
        'description' => 'Base clients : fiches, contacts, historique. Centre du système.',
        'route_name' => 'tenant.clients.index',
        'lifecycle_handler' => \InovCom\Clients\ClientsModule::class,
        'enabled_by_default' => true,
        'group' => 'commercial',
        'menu_order' => 10,
        'icon' => 'users',
        'permission' => 'clients.view',
        'tenant_types' => ['bat'],
    ],
    'offres' => [
        'core' => true,
        'label' => 'Offres',
        'description' => 'Réception des demandes : chantier, maintenance ou prestation ponctuelle.',
        'route_name' => 'tenant.offres.index',
        'lifecycle_handler' => \InovCom\Offres\OffresModule::class,
        'enabled_by_default' => true,
        'group' => 'commercial',
        'menu_order' => 30,
        'icon' => 'folder',
        'permission' => 'offres.view',
        'tenant_types' => ['bat'],
    ],
    'devis' => [
        'core' => true,
        'label' => 'Devis',
        'description' => 'Élaboration et soumission des devis. Historique et statuts.',
        'route_name' => 'tenant.devis.index',
        'lifecycle_handler' => \InovCom\Devis\DevisModule::class,
        'enabled_by_default' => true,
        'group' => 'commercial',
        'menu_order' => 35,
        'icon' => 'document',
        'permission' => 'devis.view',
        'tenant_types' => ['bat'],
    ],
    'items' => [
        'core' => false,
        'label' => 'Articles',
        'description' => 'Catalogue produits/services, unités, tarifs.',
        'route_name' => 'tenant.items.index',
        'lifecycle_handler' => \InovCom\Items\ItemsModule::class,
        'enabled_by_default' => false, // optional: not a default module; enable per tenant
        'migration_tag' => 'inovcom-items-migrations',
        'group' => 'commercial',
        'menu_order' => 40,
        'icon' => 'shopping-bag',
        'permission' => 'items.view',
        'tenant_types' => ['bat'],
    ],
    'projets' => [
        'core' => true,
        'label' => 'Chantiers & projets',
        'description' => 'Exécution des chantiers : phases, tâches, budget et avancement.',
        'route_name' => 'tenant.projets.index',
        'route_pattern' => 'tenant.projets*',
        'lifecycle_handler' => \InovCom\Projets\ProjetsModule::class,
        'enabled_by_default' => true,
        'group' => 'operations',
        'subgroup' => 'services_exec',
        'menu_order' => 38,
        'icon' => 'building',
        'permission' => 'projets.view',
        'tenant_types' => ['bat'],
    ],
    'prestations' => [
        'core' => true,
        'label' => 'Prestations ponctuelles',
        'description' => 'Missions courtes, dépannages et interventions rapides facturables.',
        'route_name' => 'tenant.prestations.index',
        'route_pattern' => 'tenant.prestations*',
        'lifecycle_handler' => \InovCom\Projets\ProjetsModule::class,
        'enabled_by_default' => true,
        'group' => 'operations',
        'subgroup' => 'services_exec',
        'menu_order' => 39,
        'icon' => 'tool',
        'permission' => 'projets.view',
        'tenant_types' => ['bat'],
    ],
    'planning' => [
        'core' => true,
        'label' => 'Planning',
        'description' => 'Calendrier des rendez-vous, visites terrain, réunions et jalons de projet.',
        'route_name' => 'tenant.planning.index',
        'lifecycle_handler' => \InovCom\Planning\PlanningModule::class,
        'enabled_by_default' => true,
        'group' => 'operations',
        'subgroup' => 'services_pilot',
        'menu_order' => 52,
        'icon' => 'calendar',
        'permission' => 'planning.view',
        'tenant_types' => ['bat'],
    ],
    'suivi' => [
        'core' => true,
        'label' => 'Suivi terrain',
        'description' => 'Kanban des tâches projet, rapports journaliers, incidents, PV de réception client.',
        'route_name' => 'tenant.suivi.board',
        'lifecycle_handler' => \InovCom\Suivi\SuiviModule::class,
        'enabled_by_default' => true,
        'group' => 'operations',
        'subgroup' => 'services_pilot',
        'menu_order' => 53,
        'icon' => 'clipboard',
        'permission' => 'suivi.view',
        'tenant_types' => ['bat'],
    ],
    'maintenance' => [
        'core' => true,
        'label' => 'Maintenance',
        'description' => 'Contrats SLA, ordres de maintenance, interventions terrain.',
        'route_name' => 'tenant.maintenance.orders.index',
        'route_pattern' => 'tenant.maintenance*',
        'lifecycle_handler' => \InovCom\Maintenance\MaintenanceModule::class,
        'enabled_by_default' => true,
        'group' => 'operations',
        'subgroup' => 'services_exec',
        'menu_order' => 40,
        'icon' => 'tool',
        'permission' => 'maintenance.view',
        'tenant_types' => ['bat'],
    ],
    'facturation' => [
        'core' => true,
        'label' => 'Facturation',
        'description' => 'Factures, suivi des paiements.',
        'route_name' => 'tenant.facturation.index',
        'lifecycle_handler' => \InovCom\Facturation\FacturationModule::class,
        'enabled_by_default' => true,
        'group' => 'finance',
        'menu_order' => 42,
        'icon' => 'chart',
        'permission' => 'facturation.view',
        'tenant_types' => ['bat'],
    ],
    'achats' => [
        'core' => true,
        'label' => 'Achats',
        'description' => 'Bons de commande, fournisseurs, réception, validation des achats.',
        'route_name' => 'tenant.achats.index',
        'lifecycle_handler' => \InovCom\Achats\AchatsModule::class,
        'enabled_by_default' => true,
        'group' => 'finance',
        'menu_order' => 45,
        'icon' => 'shopping-bag',
        'permission' => 'achats.view',
        'tenant_types' => ['bat'],
    ],
    'dms' => [
        'core' => true,
        'label' => 'Documents',
        'description' => 'Bibliothèque de documents, pièces jointes, plans, contrats.',
        'route_name' => 'tenant.dms.index',
        'lifecycle_handler' => \InovCom\Dms\DmsModule::class,
        'enabled_by_default' => true,
        'group' => 'resources',
        'menu_order' => 55,
        'icon' => 'document',
        'permission' => 'dms.view',
        'tenant_types' => ['bat'],
    ],
    'stock' => [
        'core'               => true,
        'label'              => 'Stock',
        'description'        => 'Gestion des stocks par mouvements : produits, entrepôts, entrées/sorties/transferts.',
        'route_name'         => 'tenant.stock.index',
        'lifecycle_handler'  => \InovCom\Stock\StockModule::class,
        'enabled_by_default' => true,
        'group'              => 'operations',
        'subgroup'           => 'services_supply',
        'menu_order'         => 56,
        'icon'               => 'folder',
        'permission'         => 'stock.view',
        'tenant_types'       => ['bat'],
    ],
    'logistique' => [
        'core'               => true,
        'label'              => 'Logistique',
        'description'        => 'Livraisons de matériaux, véhicules, chauffeurs, déduction automatique du stock.',
        'route_name'         => 'tenant.logistique.index',
        'lifecycle_handler'  => \InovCom\Logistique\LogistiqueModule::class,
        'enabled_by_default' => true,
        'group'              => 'operations',
        'subgroup'           => 'services_supply',
        'menu_order'         => 57,
        'icon'               => 'folder',
        'permission'         => 'logistique.view',
        'tenant_types'       => ['bat'],
    ],
    'rh' => [
        'core'              => true,
        'label'             => 'RH & Paie',
        'description'       => 'Gestion des employés, fiches de paie, congés et absences.',
        'route_name'        => 'tenant.rh.index',
        'lifecycle_handler' => \InovCom\Rh\RhModule::class,
        'enabled_by_default'=> true,
        'group'             => 'rh',
        'menu_order'        => 60,
        'icon'              => 'users',
        'permission'        => 'rh.view',
        'tenant_types'      => ['bat'],
    ],
    'users' => [
        'core' => true,
        'label' => 'Utilisateurs',
        'description' => 'Utilisateurs, rôles et permissions du tenant.',
        'route_name' => 'tenant.users.index',
        'lifecycle_handler' => \InovCom\Users\UsersModule::class,
        'enabled_by_default' => true,
        'group' => 'system',
        'menu_order' => 20,
        'icon' => 'users',
        'permission' => 'users.view',
        'tenant_types' => [],
    ],
    'configuration' => [
        'core' => true,
        'label' => 'Configuration',
        'description' => 'Nom de l\'entreprise, message de bienvenue et paramètres du portail.',
        'route_name' => 'tenant.configuration.index',
        'lifecycle_handler' => \InovCom\Branding\BrandingModule::class,
        'enabled_by_default' => true,
        'group' => 'system',
        'icon' => 'cog',
        'permission' => 'configuration.view',
        'menu_order' => 90,
        'tenant_types' => [],
    ],
];
